---
- name: Create AGE Secret
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: v1
      kind: Secret
      type: Opaque
      metadata:
        name: sops-age-keys
        namespace: openshift-gitops
      data:
        key.txt: |
          {{ openshift_gitops_ksops_age_keys | default('') | b64encode }}

- name: Apply KSOPS patch
  kubernetes.core.k8s:
    state: patched
    api_version: argoproj.io/v1beta1
    kind: ArgoCD
    name: openshift-gitops
    namespace: openshift-gitops
    definition:
      spec:
        kustomizeBuildOptions: "--enable-alpha-plugins --enable-exec"
        repo:
          resources:
            limits:
              cpu: '1'
              memory: 1Gi
            requests:
              cpu: 250m
              memory: 256Mi
          env:
            - name: XDG_CONFIG_HOME
              value: /.config
            - name: SOPS_AGE_KEY_FILE
              value: /.config/sops/age/key.txt
          volumes:
            - name: custom-tools
              emptyDir: {}
            - name: sops-age-keys
              secret:
                secretName: sops-age-keys
          initContainers:
            - name: install-ksops
              image: viaductoss/ksops:latest-amd64
              command: ["/bin/sh", "-c"]
              args:
                - 'echo "Installing KSOPS..."; cp ksops /custom-tools/; cp $GOPATH/bin/kustomize /custom-tools/; echo "Done.";'
              volumeMounts:
                - mountPath: /custom-tools
                  name: custom-tools
          volumeMounts:
            - mountPath: /usr/local/bin/kustomize
              name: custom-tools
              subPath: kustomize
            - mountPath: /usr/local/bin/ksops
              name: custom-tools
              subPath: ksops
            - mountPath: /.config/sops/age/key.txt
              name: sops-age-keys
              subPath: key.txt

- name: Wait for changes to be applied
  kubernetes.core.k8s_info:
    api_version: argoproj.io/v1beta1
    kind: ArgoCD
    name: openshift-gitops
    namespace: openshift-gitops
  register: argocd
  until: "\"KSOPS\" in argocd['resources'][0]['spec']['repo']['initContainers'][0]['args'][0] | default('')"
  retries: 60
  delay: 10
  ignore_errors: "{{ ansible_check_mode }}"
